WITH RELS (LEVEL, TABSCHEMA, TABNAME, REFTABSCHEMA, REFTABNAME) AS
(
    SELECT
        0,
        TABSCHEMA,
        TABNAME,
        '',
        ''
    FROM
        SYSCAT.TABLES
    WHERE
--        TABSCHEMA='MYSCHEMA'
        TABSCHEMA NOT LIKE 'SYS%'
        AND (TABSCHEMA,TABNAME) NOT IN
            (SELECT TABSCHEMA, TABNAME FROM SYSCAT.REFERENCES)
    UNION ALL
    SELECT
        R.LEVEL + 1, S.TABSCHEMA, S.TABNAME, S.REFTABSCHEMA, S.REFTABNAME
        FROM       SYSCAT.REFERENCES S , RELS R WHERE
        S.REFTABNAME  = R.TABNAME
        AND        S.REFTABSCHEMA = R.TABSCHEMA
        AND        R.LEVEL < 10
        AND        S.REFTABNAME || S.REFTABSCHEMA != S.TABNAME || S.TABSCHEMA
           
)
SELECT DISTINCT LEVEL, substr(TABSCHEMA,1,20) tabschema, substr(TABNAME,1,20) tabname, substr(REFTABSCHEMA,1,20)reftabschema, substr(REFTABNAME,1,20) reftabname FROM RELS order by LEVEL ASC;
